<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
	<Nullable>enable</Nullable>
	<BaseOutputPath>.\bin</BaseOutputPath>
    <TiaWorkerVersion Condition="'$(TiaWorkerVersion)' == ''">20</TiaWorkerVersion>
    <DefineConstants>$(DefineConstants);TIA_MCP_V$(TiaWorkerVersion)</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest" Version="3.9.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TiaMcpServer\TiaMcpServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
</Project>
